name: Stage - Build and Deploy Pipeline
run-name: "Stage - Build and Deploy #${{ github.run_number }}"

on:
  push:
    branches: main

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/template-build.yml
    with:
      upload-artifact: true
      app-solution: ./EverydayRewardsReceipts.Downloader.sln
      app-publish-project: ./src/Presentation/WebApi/EverydayRewardsReceipts.Downloader.Presentation.WebApi.csproj
  cd:
    name: CD
    needs: ci
    uses: ./.github/workflows/template-deploy.yml
    with:
      environment: staging
      resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
      bicepparam-file: ./infra/staging.bicepparam
